# Generated by Django 5.2.3 on 2025-07-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_empresas/'),
        ),
    ]
