# Generated by Django 5.2.3 on 2025-07-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_empresaprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_estudiantes/'),
        ),
    ]
