# Generated by Django 5.2.3 on 2025-06-19 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacantes', '0002_remove_vacante_rango_salario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('institucion', models.CharField(max_length=150, verbose_name='Institución educativa')),
                ('motivo', models.TextField(blank=True, verbose_name='¿Por qué deseas aplicar?')),
                ('cv', models.FileField(blank=True, null=True, upload_to='postulaciones/cvs/', verbose_name='Currículum Vitae (PDF)')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to=settings.AUTH_USER_MODEL)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='vacantes.vacante')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'ordering': ['-fecha_postulacion'],
                'unique_together': {('estudiante', 'vacante')},
            },
        ),
    ]
