# Generated by Django 5.2.3 on 2025-06-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Entrevista', 'En Entrevista')], default='Pendiente', max_length=50),
        ),
    ]
