# Generated by Django 5.2.3 on 2025-06-19 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulaciones', '0002_postulacion_status'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='users.estudianteprofile'),
        ),
    ]
