# Generated by Django 5.2.3 on 2025-07-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulaciones', '0003_alter_postulacion_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='email',
            field=models.EmailField(default='ejemplo@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='telefono_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='nombre_completo',
            field=models.CharField(max_length=150, verbose_name='Nombre y apellido'),
        ),
    ]
