# Generated by Django 5.2.3 on 2025-07-17 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulaciones', '0005_notificacion'),
        ('users', '0003_estudianteprofile_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='fecha_creada',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='leido',
            new_name='leida',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='users.estudianteprofile'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
