# Generated by Django 5.2.3 on 2025-06-18 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('requerimientos', models.TextField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('rango_salario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_publicada', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empresaprofile')),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
                'ordering': ['-fecha_publicada'],
            },
        ),
    ]
