# Generated by Django 5.2.3 on 2025-06-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacante',
            name='rango_salario',
        ),
    ]
