# Generated by Django 5.2.3 on 2025-06-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0002_remove_vacante_rango_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='cantidad_vacantes',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de vacantes'),
        ),
        migrations.AddField(
            model_name='vacante',
            name='duracion',
            field=models.CharField(default='Indefinido', help_text='Ej: 3-6 meses', max_length=50, verbose_name='Duración del puesto'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='activo',
            field=models.BooleanField(default=True, help_text='Las vacantes activas serán visibles para los candidatos', verbose_name='Activar vacante'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción del puesto'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='fecha_limite',
            field=models.DateField(verbose_name='Fecha límite de la publicación'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='requerimientos',
            field=models.TextField(verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Puesto de vacante'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='ubicacion',
            field=models.CharField(max_length=100, verbose_name='Ubicación'),
        ),
    ]
