# Generated by Django 5.2.3 on 2025-07-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0003_vacante_cantidad_vacantes_vacante_duracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='duracion',
            field=models.CharField(help_text='Ej: 3-6 meses', max_length=50, verbose_name='Duración del puesto'),
        ),
    ]
